<a href="https://colab.research.google.com/github/Devansh-0/COVID-19/blob/main/Covid_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pwd

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/


/content/drive/My Drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive


In [ ]:
#importing files
import pandas as pd
df = pd.read_csv('/Cleaned-Data.csv')
df.head()


Fever  Tiredness  Dry-Cough  ...  Contact_No  Contact_Yes  Country
0      1          1          1  ...         0.0          1.0    China
1      1          1          1  ...         1.0          0.0    China
2      1          1          1  ...         0.0          0.0    China
3      1          1          1  ...         0.0          1.0    China
4      1          1          1  ...         1.0          0.0    China

[5 rows x 27 columns]

In [ ]:
df.shape

(170739, 27)

In [ ]:
df['Severity_Severe'].value_counts()

0.0    128054
1.0     42684
Name: Severity_Severe, dtype: int64

In [ ]:
x = df.iloc[60000:75000,[0,1,2,3,4,5,6,7,8,9,10]].values
y = df.iloc[60000:75000,22].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [ ]:
x_train[1]

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0])

In [ ]:
x_train.shape

(11250, 11)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred,y_test)*100

73.89333333333333

In [ ]:
confusion_matrix(y_pred,y_test)

array([[2771,  979],
       [   0,    0]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       1.00      0.74      0.85      3750
         1.0       0.00      0.00      0.00         0

    accuracy                           0.74      3750
   macro avg       0.50      0.37      0.42      3750
weighted avg       1.00      0.74      0.85      3750



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svm_classifier = SVC()

parameters = [{'C':[1,10,100,1000],'kernel':['linear'],
               'C':[1,10,100,1000],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]


grid_search = GridSearchCV(estimator=svm_classifier,param_grid = parameters,
                           scoring='accuracy',cv = 10)

grid_search =grid_search.fit(x_train,y_train)

In [ ]:
grid_search.best_score_

0.7536888888888889

In [ ]:
grid_search.best_params_

{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}

In [ ]:
svm_classifier =SVC(gamma=0.1,kernel='rbf')
svm_classifier.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svm_classifier.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred,y_test)

0.7389333333333333

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics 

In [ ]:
DTC= DecisionTreeClassifier()
DTC.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred= DTC.predict(x_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
accuracy_score(y_test,y_pred)

0.7389333333333333

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       1.00      0.74      0.85      3750
         1.0       0.00      0.00      0.00         0

    accuracy                           0.74      3750
   macro avg       0.50      0.37      0.42      3750
weighted avg       1.00      0.74      0.85      3750



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
